name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          gcc -ftest-coverage -fprofile-arcs -O0 -o test test.c example.c
          ./test
          gcov -abcfu example.c
      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: example.c
