name: Regression / mpi
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
      - run: mpicc hello.c
      - run: mpirun -n 2 ./a.out
